Add `skip_wait_on_job_termination` option for dataflow job resources
hashicorp/terraform-provider-google pull request #10728
Opened 2021-12-10 15:09 UTC by n-oden

This addresses https://github.com/hashicorp/terraform-provider-google/issues/10559

See also https://github.com/hashicorp/terraform-provider-google-beta/pull/3868

2022-01-03 14:47 UTC, n-oden commented
@ScottSuarez Happy new year!  Did you have any thoughts on this one?

2022-01-04 17:47 UTC, ScottSuarez commented
I think I understand the use case but could you elaborate or go into more detail on your change?

2022-01-05 19:00 UTC, n-oden commented
@ScottSuarez https://github.com/hashicorp/terraform-provider-google/issues/10559 goes into a lot more detail; the 5s summary is "sometimes draining streaming dataflow jobs takes a ridiculously long time" -- minutes to hours depending on what sort of internal windowing/watermark strategy your job is using.  This means that potentially your terraform workspace is locked for that entire time while waiting for the job to drain.

With this in place, operators will have the option of waiting only until the job reaches the DRAINING state before moving on.  Obviously this has the caveat that if you try to create a replacement job with the same name before the job actually exits it will fail, hence the digression about random_id in the doc examples.

2022-01-14 21:03 UTC, n-oden commented
@rileykarson happy new year!  Thoughts on this?

2022-03-13 14:31 UTC, n-oden commented
@ScottSuarez @rileykarson nudge?  If this isn't an approach to #10559 that you like, please let me know.

2022-03-15 22:55 UTC, ScottSuarez commented
taking over review here. I'll give this a look over soon

2022-03-18 17:41 UTC, ScottSuarez requested changes
Could you also add a test case to the testsuite for this resource and ensure it passes

https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_dataflow_job_test.go

2022-03-18 17:41 UTC, ScottSuarez commented on google/resource_dataflow_job.go
> +	}
This logic is repeated several times. Can you extrapolate this to a function

```golang
func isDataflowJobResourceDeleted(state string, skipWait bool) bool {
	_, stopQuery := dataflowTerminalStatesMap[state]
	if !stopQuery && skipWait {
		_, stopQuery = dataflowTerminatingStatesMap[d.Get("state").(string)]
	}
	return stopQuery
}
```

2022-03-18 20:23 UTC, n-oden commented
All reasonable requests!  I'll try to get it sorted out both here and in the beta-provider PR on monday or tuesday.

2022-03-18 21:55 UTC, ScottSuarez commented
Can you make the changes against the upstream repository https://github.com/GoogleCloudPlatform/magic-modules

We use this to generate the two version of the provider. Tag me on the PR when you open it

2022-03-22 17:44 UTC, n-oden commented
continued in https://github.com/GoogleCloudPlatform/magic-modules/pull/5844

2022-03-22 17:44 UTC, closed without merging