Docs: Update `value_extractor` usage in logs-based metrics
hashicorp/terraform-provider-google pull request #14339
Opened 2023-04-17 18:16 UTC by sahya

## What
This pull request updates the usage of `value_extractor` in logs-based metrics for distribution value type. The changes include:

- Added clarification that `value_extractor` is required for distribution logs-based metrics
- Provided examples for `EXTRACT(field)` and `REGEXP_EXTRACT(field, regex)`
- Clarified the arguments for `value_extractor` - "field" and "regex"
- Mentioned the requirement of correct regular expression for the "regex" argument
- Highlighted the requirement of `value_extractor` and `bucket_options` for DISTRIBUTION value type logs-based metrics

These changes aim to improve the understanding and usage of `value_extractor` in logs-based metrics. Kindly review and provide feedback. Thank you.

## Why
When defining a distribution logs-based metric today, I encountered a confusing explanation and error. It was as follows.
* Unsure how to write `REGEXP_EXTRACT`.
* When defining a distribution logs-based metric, it is unsure what optional fields are mandatory.
* Error with capture group due to Google's API, even though the capture group is correct. The regular expression was written inaccurately.

Therefore, I just create this pull request. I would be happy if this PR becomes a guide to help someone not get lost on the road about this section.

If you find any incorrect notations in the documentation, such as backquotes or double quotes, I would appreciate it if you could correct them.

2023-04-17 21:38 UTC, melinath requested changes
Thanks for your contribution! This file is managed by Magic Modules, so you'll need to contribute there: https://github.com/GoogleCloudPlatform/magic-modules Instructions are in the README.

2024-01-04 12:58 UTC, sahya commented
related https://github.com/GoogleCloudPlatform/magic-modules/pull/7759

2024-01-04 13:30 UTC, sahya commented
@melinath 
Hi, I could not find the method So I have no choice. 
Excuse, me. Could you please create my intention changes from you?

2024-01-04 16:57 UTC, melinath commented
Hi @sahya - Unfortunately I won't be able to migrate your proposed change myself. However, I can hopefully point you in the right direction! It looks like this resource is generated using magic modules, so the documentation is all coming from this file: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/logging/Metric.yaml

For information about how to preview the results, see our new docsite: https://googlecloudplatform.github.io/magic-modules/develop/resource/#add-documentation

2024-01-04 23:14 UTC, sahya commented
@melinath I appreciate you! Your help is really very helpful. I will try it when I have time.

2024-09-13 21:52 UTC, closed without merging

2024-09-13 21:52 UTC, melinath commented
belatedly, sounds good and best of luck! Closing this just to tidy up.