Update CHANGELOG.md
hashicorp/terraform-provider-google pull request #15162
Opened 2023-07-13 19:05 UTC by trodge

2023-07-17 17:20 UTC, shuyama1 requested changes

2023-07-17 17:20 UTC, shuyama1 commented on CHANGELOG.md
> +* **New Resource:** `google_network_services_gateway` (ga) ([#15112](https://github.com/hashicorp/terraform-provider-google/pull/15112))
```suggestion
* **New Resource:** `google_cloudbuildv2_connection` ([#15098](https://github.com/hashicorp/terraform-provider-google/pull/15098))
* **New Resource:** `google_cloudbuildv2_repository` ([#15098](https://github.com/hashicorp/terraform-provider-google/pull/15098))
* **New Resource:** `google_gkeonprem_bare_metal_admin_cluster` ([#15099](https://github.com/hashicorp/terraform-provider-google/pull/15099))
* **New Resource:** `google_network_security_address_group` ([#15111](https://github.com/hashicorp/terraform-provider-google/pull/15111))
* **New Resource:** `google_network_security_gateway_security_policy_rule` ([#15112](https://github.com/hashicorp/terraform-provider-google/pull/15112))
* **New Resource:** `google_network_security_gateway_security_policy` ([#15112](https://github.com/hashicorp/terraform-provider-google/pull/15112))
* **New Resource:** `google_network_security_url_lists` ([#15112](https://github.com/hashicorp/terraform-provider-google/pull/15112))
* **New Resource:** `google_network_services_gateway` ([#15112](https://github.com/hashicorp/terraform-provider-google/pull/15112))
```

2023-07-17 17:20 UTC, shuyama1 commented on CHANGELOG.md
> +* cloudbuildv2: added `gitlab_config` field to `google_cloudbuildv2_connection` resource (beta) ([#15053](https://github.com/hashicorp/terraform-provider-google/pull/15053))
```suggestion
* cloudbuild: added `repository_event_config` field to `google_cloudbuild_trigger` resource ([#15098](https://github.com/hashicorp/terraform-provider-google/pull/15098))
```
We can remove beta changes from GA provider

2023-07-17 17:20 UTC, shuyama1 commented on CHANGELOG.md
> +* container: made `monitoring_config.enable_components` optional on `google_container_cluster`(ga) ([#15131](https://github.com/hashicorp/terraform-provider-google/pull/15131))
```suggestion
* container: made `monitoring_config.enable_components` optional on `google_container_cluster` ([#15131](https://github.com/hashicorp/terraform-provider-google/pull/15131))
```

2023-07-18 20:56 UTC, melinath approved these changes

2023-07-18 20:56 UTC, melinath commented on CHANGELOG.md
> +* monitoring: fixed an issue causing `google_monitoring_monitored_project` to appear to be deleted ([#15140](https://github.com/hashicorp/terraform-provider-google/pull/15140))
resolved in patch 
```suggestion
```

2023-07-18 20:56 UTC, merged