Release 4.80.0 change logs
hashicorp/terraform-provider-google pull request #15619
Opened 2023-08-24 21:22 UTC by ScottSuarez

2023-08-24 21:24 UTC, slevenick requested changes

2023-08-24 21:24 UTC, slevenick commented on CHANGELOG.md
> +UNKNOWN CHANGELOG TYPE:
Most of these look like enhancements?

2023-08-24 21:24 UTC, slevenick commented on CHANGELOG.md
> +* alloydb: fixed import path doc for `google_alloydb_instance` ([#15578](https://github.com/hashicorp/terraform-provider-google/pull/15578))
Doc-only?

2023-08-24 21:24 UTC, slevenick commented on CHANGELOG.md
> +* **New Resource:** `google_iam_deny_policy` (ga only) ([#15571](https://github.com/hashicorp/terraform-provider-google/pull/15571))
```suggestion
* **New Resource:** `google_iam_deny_policy` ([#15571](https://github.com/hashicorp/terraform-provider-google/pull/15571))
```

2023-08-24 21:24 UTC, slevenick commented on CHANGELOG.md
> +* **New Resource:** dataform_repository_workflow_config (beta) ([#15543](https://github.com/hashicorp/terraform-provider-google/pull/15543))
Remove beta only

2023-08-24 21:24 UTC, slevenick commented on CHANGELOG.md
> +* clouddeploy: promoted `multi_target` to GA in `google_clouddelploy_target` ([#15564](https://github.com/hashicorp/terraform-provider-google/pull/15564))
"added `multi_target` in ..."

2023-08-24 21:24 UTC, slevenick commented on CHANGELOG.md
> +* compute: added `security_policy` field to `google_compute_target_instance` resource (beta) ([#15566](https://github.com/hashicorp/terraform-provider-google/pull/15566))
Remove

2023-08-24 21:24 UTC, slevenick commented on CHANGELOG.md
> +* gkehub: promoted the `google_gke_hub_feature_membership` resource to GA ([#15604](https://github.com/hashicorp/terraform-provider-google/pull/15604))
Reword

2023-08-24 21:31 UTC, ScottSuarez commented on CHANGELOG.md
> +* **New Resource:** dataform_repository_workflow_config (beta) ([#15543](https://github.com/hashicorp/terraform-provider-google/pull/15543))
```suggestion
```

2023-08-24 21:31 UTC, ScottSuarez commented on CHANGELOG.md
> +* clouddeploy: promoted `multi_target` to GA in `google_clouddelploy_target` ([#15564](https://github.com/hashicorp/terraform-provider-google/pull/15564))
```suggestion
* clouddeploy: added `multi_target` to in `google_clouddelploy_target` ([#15564](https://github.com/hashicorp/terraform-provider-google/pull/15564))
```

2023-08-24 21:43 UTC, ScottSuarez commented on CHANGELOG.md
> +* alloydb: fixed import path doc for `google_alloydb_instance` ([#15578](https://github.com/hashicorp/terraform-provider-google/pull/15578))
removed

2023-08-25 12:40 UTC, slevenick approved these changes

2023-08-25 22:11 UTC, ScottSuarez commented on CHANGELOG.md
> +* **New Resource:** `google_gke_hub_membership_rbac_role_binding` ([#15544](https://github.com/hashicorp/terraform-provider-google/pull/15544))
```suggestion
```

hotfixing removal of this resource

2023-08-25 22:11 UTC, ScottSuarez commented on CHANGELOG.md
> +* **New Resource:** `google_gke_hub_membership_rbac_role_binding` ([#15544](https://github.com/hashicorp/terraform-provider-google/pull/15544))
https://github.com/GoogleCloudPlatform/magic-modules/pull/8776

2023-08-25 23:09 UTC, ScottSuarez commented on CHANGELOG.md
> +* **New Resource:** `google_gke_hub_membership_rbac_role_binding` ([#15544](https://github.com/hashicorp/terraform-provider-google/pull/15544))
https://github.com/hashicorp/terraform-provider-google/commit/feb52d5adb7591bff1b7932471fe82e2feb4d2f7

2023-08-25 23:09 UTC, ScottSuarez commented
Cherry picked resource removal. Was a beta only resource.
https://github.com/hashicorp/terraform-provider-google/commit/feb52d5adb7591bff1b7932471fe82e2feb4d2f7

Already updated release notes to reflect.

2023-08-28 17:13 UTC, merged