Add NotificationConfig to google_container_cluster
hashicorp/terraform-provider-google pull request #7338
Opened 2020-09-23 13:47 UTC by freddd

This PR aims to introduce a new attribute called `notification_config` on `google_container_cluster` which enables a feature to send pubsub notifications on cluster upgrades. It's currently in beta. As this is my first contributing to a provider, I'm a bit unsure how to test it past writing tests. 

References:
* https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-upgrade-notifications?hl=el
* https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.NotificationConfig

Closes #7337

2020-09-23 14:39 UTC, megan07 requested changes
Hi @freddd!  Thank you so much for your contribution! This looks great!
I've added a few comments in the code, but have a few more general thoughts.
First, I see this is beta-only. Our `google-beta` provider is actually in a different repository, however, both repositories are generated from an upstream repository called [magic-modules](https://github.com/GoogleCloudPlatform/magic-modules). So I'm going to direct you there, you can make your changes in `third_party/terraform/resources/resource_container_cluster.go.erb`.  You'll see in that file that there are some blocks surrounded by 
```
<% unless version == 'ga' -%>
...
<% end -%>
```
The code in those blocks is only generated for `google-beta`, so you can put your code in those blocks.
I think the last things missing from this are setting it in state and allowing it to be updated.
To set it in the state file, you'll want to add a `d.Set("notification_config", flattenNotificationConfig(cluster.NotificationConfig));` in the Read function, where the flatten function will take the object returned from the API and translate it back into the Terraform Schema.
You'll then also want to check for/make updates in the Update function.
Please feel free to add me as the reviewer there, and don't hesitate to ask any questions along the way! I can run the tests for you once the new PR is created in magic-modules.
Thanks again!

2020-09-23 14:39 UTC, megan07 commented on google/resource_container_cluster.go
> +			"notification_config": {
Because this is technically an object and not a list, we will want to add `MaxItems: 1` to this block.

2020-09-23 14:39 UTC, megan07 commented on google/resource_container_cluster.go
> +						"pubsub": {
This can be `Required: true` since it's the only attribute on the `notification_config` block.

2020-09-23 14:39 UTC, megan07 commented on google/resource_container_cluster.go
> +										Required:    true,
If `enabled` is `false`, is `topic` still required? Do we maybe want to make this `Optional: true`?

2020-09-24 08:09 UTC, freddd commented
Thanks for the feedback @megan07 - really appreciate it. I will open a PR in Magic Modules shortly. Closing this meanwhile.

2020-09-24 08:09 UTC, closed without merging