Allow dependabot to check go dependencies
hashicorp/terraform-provider-google pull request #8082
Opened 2020-12-24 01:33 UTC by jlosito

This change allows dependabot to check go dependencies which this project uses and automatically submit PRs with version bumps.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

2020-12-24 01:58 UTC, ndmckinley commented
I don't have much of an opinion on that, but Cameron may?

2021-01-05 16:27 UTC, c2thorn commented
I'm not quite sure we want automated version bumps of our go dependencies. I'll check with the team

2021-01-05 21:06 UTC, c2thorn commented
Looks like this is something we want to try!

2021-01-05 21:08 UTC, c2thorn requested changes
@jlosito Do you know if there is a way to modify the pull request message? I'd want to add a message to reviewers reminding them to keep https://github.com/hashicorp/terraform-provider-google-beta in sync as well.

2021-01-05 21:17 UTC, jlosito commented
I'm not sure too about that one. 

I just double-scanned the docs again. It looks like there's a way to change commit message, not what we're looking for. It doesn't look like there's a way to change the comment that the bot would leave when it creates the pull request.

I'd be willing to open up another PR against the beta provider. I also use that one on a daily basis. The idea being if both projects have the same config, I would imagine the bot would open pull requests against both of the projects at the same time.

2021-01-05 22:21 UTC, jlosito commented
https://github.com/hashicorp/terraform-provider-google-beta/pull/2832

2021-01-05 22:22 UTC, merged

2021-01-05 22:32 UTC, jlosito commented
Looks like someone is going to be busy will all of the PRs the bot just submitted. 😆 Have fun!