Update documentation for sql instance
hashicorp/terraform-provider-google pull request #8445
Opened 2021-02-11 11:02 UTC by vanessabodard-voi

This is a PR to update the documentation.
By using the ON_DEMAND option, I had this error:
`Error: Error, failed to update instance settings for : googleapi: Error 400: Invalid request: Invalid flag for instance role: GCE instances do not support 'ON_DEMAND' activation policy.., invalid`

Based on this document (https://cloud.google.com/sql/docs/mysql/start-stop-restart-instance), it looks like the option ON_DEMAND is not an available.

2021-02-17 22:02 UTC, melinath requested changes
Sorry for the delayed review! I think that we should probably match the [documentation you linked](https://cloud.google.com/sql/docs/mysql/start-stop-restart-instance) and only mention ALWAYS and NEVER.

2021-04-30 20:59 UTC, melinath commented
@vanessabodard-voi Hi, are you still interested in working on this PR? It's just waiting on a small update from you.

2021-05-01 08:57 UTC, vanessabodard-voi commented
> @vanessabodard-voi Hi, are you still interested in working on this PR? It's just waiting on a small update from you.

Hej,
Sorry, I missed the notification for your review.
Updated !
Thx.

2021-05-03 16:20 UTC, melinath approved these changes
LGTM - thanks!

2021-05-03 21:13 UTC, merged