Add `path` on GCS targets in `google_storage_transfer_job`
hashicorp/terraform-provider-google pull request #8931
Opened 2021-04-16 11:10 UTC by bambuchaAdm

Fix #8704 

It is my first contribution and i am little concern about style in documentation. It was copied out form REST api docs, but could be little confusing on usage. What do you think.

2021-04-16 17:49 UTC, ScottSuarez requested changes

2021-04-16 17:49 UTC, ScottSuarez commented on google/resource_storage_transfer_job.go
> +				Default:      "",
we should remove the default value here. Ideally we won't send this value if not set by the user. 

If the value is returned by the api after creation use `Computed: true`

2021-04-16 17:49 UTC, ScottSuarez commented on google/resource_storage_transfer_job.go
> +		Path:       gcsData["path"].(string),
conditionally set this based on whether it exists in the map

2021-04-16 17:49 UTC, ScottSuarez commented on google/resource_storage_transfer_job.go
> +		"path":        gcsData.Path,
This is fine if we are using `Computed: true` in the schema definition.

2021-04-30 14:26 UTC, bambuchaAdm commented
Property marked as computed. Is this mark would prevent engine from detect difference if this variable would be not specified in resource ? I also made little amendment in first commit message to reference original issue.

2021-06-24 05:45 UTC, bambuchaAdm commented
@ScottSuarez Would you like to make again review on code after requested fixes ?

2021-06-30 20:58 UTC, ScottSuarez commented
ah this has escaped me, let me take a looksee. sorry about that /gcbrun

2021-08-19 22:41 UTC, ScottSuarez commented
gosh sorry about the delay ! let me upstream the change. looks good

2021-08-19 22:59 UTC, ScottSuarez commented
superseded by https://github.com/GoogleCloudPlatform/magic-modules/pull/5117

2021-08-19 22:59 UTC, closed without merging