3.76.0 changelogs
hashicorp/terraform-provider-google pull request #9627
Opened 2021-07-23 20:20 UTC by c2thorn

2021-07-23 20:44 UTC, melinath requested changes
LGTM apart from the one thing

2021-07-23 20:44 UTC, melinath commented on CHANGELOG.md
> +* composer: added field `maintenance_window` to resource `google_composer_environment` (beta) ([#9595](https://github.com/hashicorp/terraform-provider-google/pull/9595))
This is beta-only

2021-07-23 21:33 UTC, melinath approved these changes
LGTM

2021-07-26 16:22 UTC, megan07 commented on CHANGELOG.md
> +* Fixed ordering of `budget_filter. projects` on `google_billing_budget` ([#9598](https://github.com/hashicorp/terraform-provider-google/pull/9598))
Does this need a service in front of it? billing maybe?

2021-07-26 16:34 UTC, megan07 approved these changes

2021-07-26 16:46 UTC, merged